Introduce liveness bug TLC finds in under a second:
```
tlc BlockingQueueFair -deadlock -note
TLC2 Version 2.18 of Day Month 20?? (rev: 3a75658)
Running breadth-first search Model-Checking with fp 28 and seed 1910712117196697030 with 1 worker on 10 cores with 7282MB heap and 64MB offheap memory [pid: 54759] (Mac OS X 12.6 aarch64, Homebrew 11.0.16.1 x86_64, MSBDiskFPSet, DiskStateQueue).
Parsing file /Users/markus/src/TLA/_specs/models/tutorials/BlockingQueue/BlockingQueueFair.tla
Parsing file /private/var/folders/7d/4x6z2cc91jl588ysynlc1tfc0000gn/T/tlc-1929026847153507125/Naturals.tla (jar:file:/Applications/TLA+%20Toolbox.app/Contents/Eclipse/tla2tools.jar!/tla2sany/StandardModules/Naturals.tla)
Parsing file /private/var/folders/7d/4x6z2cc91jl588ysynlc1tfc0000gn/T/tlc-1929026847153507125/Sequences.tla (jar:file:/Applications/TLA+%20Toolbox.app/Contents/Eclipse/tla2tools.jar!/tla2sany/StandardModules/Sequences.tla)
Parsing file /private/var/folders/7d/4x6z2cc91jl588ysynlc1tfc0000gn/T/tlc-1929026847153507125/FiniteSets.tla (jar:file:/Applications/TLA+%20Toolbox.app/Contents/Eclipse/tla2tools.jar!/tla2sany/StandardModules/FiniteSets.tla)
Parsing file /private/var/folders/7d/4x6z2cc91jl588ysynlc1tfc0000gn/T/tlc-1929026847153507125/Functions.tla (jar:file:/Applications/TLA+%20Toolbox.app/Contents/Eclipse/CommunityModules-deps.jar!/Functions.tla)
Parsing file /Users/markus/src/TLA/_specs/models/tutorials/BlockingQueue/SequencesExt.tla
Parsing file /Users/markus/src/TLA/_specs/models/tutorials/BlockingQueue/BlockingQueueSplit.tla
Parsing file /private/var/folders/7d/4x6z2cc91jl588ysynlc1tfc0000gn/T/tlc-1929026847153507125/Folds.tla (jar:file:/Applications/TLA+%20Toolbox.app/Contents/Eclipse/CommunityModules-deps.jar!/Folds.tla)
Parsing file /private/var/folders/7d/4x6z2cc91jl588ysynlc1tfc0000gn/T/tlc-1929026847153507125/FiniteSetsExt.tla (jar:file:/Applications/TLA+%20Toolbox.app/Contents/Eclipse/CommunityModules-deps.jar!/FiniteSetsExt.tla)
Parsing file /private/var/folders/7d/4x6z2cc91jl588ysynlc1tfc0000gn/T/tlc-1929026847153507125/TLC.tla (jar:file:/Applications/TLA+%20Toolbox.app/Contents/Eclipse/tla2tools.jar!/tla2sany/StandardModules/TLC.tla)
Parsing file /Users/markus/src/TLA/_specs/models/tutorials/BlockingQueue/BlockingQueue.tla
Parsing file /Users/markus/src/TLA/_specs/models/tutorials/BlockingQueue/TLAPS.tla
Semantic processing of module Naturals
Semantic processing of module Sequences
Semantic processing of module FiniteSets
Semantic processing of module Folds
Semantic processing of module Functions
Semantic processing of module FiniteSetsExt
Semantic processing of module TLC
Semantic processing of module SequencesExt
Semantic processing of module TLAPS
Semantic processing of module BlockingQueue
Semantic processing of module BlockingQueueSplit
Semantic processing of module BlockingQueueFair
Starting... (2022-10-03 14:54:40)
Implied-temporal checking--satisfiability problem has 1 branches.
Computing initial states...
Finished computing initial states: 1 distinct state generated at 2022-10-03 14:54:40.
Progress(6) at 2022-10-03 14:54:40: 30 states generated, 16 distinct states found, 0 states left on queue.
Checking temporal properties for the complete state space with 16 total distinct states at (2022-10-03 14:54:40)
Error: Temporal properties were violated.

Error: The following behavior constitutes a counter-example:

State 1: <Initial predicate>
/\ waitSeqC = <<>>
/\ waitSeqP = <<>>
/\ buffer = <<>>

State 2: <Put line 53, col 1 to line 60, col 27 of module BlockingQueueFair>
/\ waitSeqC = <<>>
/\ waitSeqP = <<>>
/\ buffer = <<p2>>

State 3: <Put line 53, col 1 to line 60, col 27 of module BlockingQueueFair>
/\ waitSeqC = <<>>
/\ waitSeqP = <<p1>>
/\ buffer = <<p2>>

State 4: <Put line 53, col 1 to line 60, col 27 of module BlockingQueueFair>
/\ waitSeqC = <<>>
/\ waitSeqP = <<p1, p2>>
/\ buffer = <<p2>>

State 5: <Get line 63, col 1 to line 70, col 27 of module BlockingQueueFair>
/\ waitSeqC = <<>>
/\ waitSeqP = <<p1>>
/\ buffer = <<>>

Back to state 3: <Put line 53, col 1 to line 60, col 27 of module BlockingQueueFair>

Finished checking temporal properties in 00s at 2022-10-03 14:54:40
30 states generated, 16 distinct states found, 0 states left on queue.
The depth of the complete state graph search is 6.
Finished in 00s at (2022-10-03 14:54:40)
```